// backend/seedProducts.js — run with: node seedProducts.js
import mongoose from "mongoose";
import dotenv from "dotenv";
import Product from "./models/Product.js";

dotenv.config();

await mongoose.connect(process.env.MONGO_URI);
console.log("✅ Connected to MongoDB");

await Product.deleteMany({});
console.log("🗑  Cleared existing products");

const products = [
  // ── Steel Furniture Works ──────────────────────────────────────
  {
    productId: "SKW-SF-001", productName: "Heavy Duty Steel Office Chair", category: "Steel Furniture Works",
    furnitureType: "Chair", steelGrade: "IS 2062", surfaceFinish: "Powder Coated", color: "Black",
    availability: "Available", finalPriceINR: 4500, basePriceINR: 5200, discountPercentage: 13,
    stockQuantity: 120, rating: 4.5, reviewsCount: 38, salesCount: 95,
    warrantyYears: 2, leadTimeDays: 7, customizationAvailable: "Yes",
    length_cm: 60, width_cm: 60, height_cm: 90, weight_kg: 12,
    loadCapacityKg: 150, usageArea: "Office", recommendedFor: "Commercial use",
    productDescription: "Heavy-duty powder-coated steel office chair with ergonomic backrest. Suitable for commercial and industrial use.",
    features: "Powder coated, Rust resistant, Ergonomic backrest, Adjustable height, Non-slip feet",
    frameThickness: "2mm", countryOfOrigin: "India", createdAt: "2024-01-01",
    imageUrl: "https://images.unsplash.com/photo-1541123437800-1bb1317badc2?w=700&q=80",
  },
  {
    productId: "SKW-SF-002", productName: "Industrial Steel Workbench", category: "Steel Furniture Works",
    furnitureType: "Table", steelGrade: "IS 2062 E250", surfaceFinish: "Powder Coated", color: "Grey",
    availability: "Available", finalPriceINR: 12500, basePriceINR: 14000, discountPercentage: 11,
    stockQuantity: 45, rating: 4.7, reviewsCount: 22, salesCount: 60,
    warrantyYears: 3, leadTimeDays: 10, customizationAvailable: "Yes",
    length_cm: 180, width_cm: 75, height_cm: 85, weight_kg: 38,
    loadCapacityKg: 500, usageArea: "Workshop", recommendedFor: "Industrial use",
    productDescription: "Heavy-duty steel workbench for workshops and factories. Custom sizes available on request.",
    features: "Heavy load capacity, Powder coated, Custom sizes available, Shelf below, Tool hooks",
    frameThickness: "3mm", countryOfOrigin: "India", createdAt: "2024-01-02",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&q=80",
  },
  {
    productId: "SKW-SF-003", productName: "Steel Storage Rack – 5 Tier", category: "Steel Furniture Works",
    furnitureType: "Rack", steelGrade: "IS 2062", surfaceFinish: "Epoxy Coated", color: "Blue/Orange",
    availability: "Available", finalPriceINR: 8200, basePriceINR: 9500, discountPercentage: 14,
    stockQuantity: 80, rating: 4.6, reviewsCount: 54, salesCount: 130,
    warrantyYears: 2, leadTimeDays: 5, customizationAvailable: "Yes",
    length_cm: 90, width_cm: 45, height_cm: 180, weight_kg: 22,
    loadCapacityKg: 300, usageArea: "Warehouse", recommendedFor: "Storage",
    productDescription: "5-tier industrial steel storage rack. Each shelf holds up to 60 kg. Easy bolt assembly.",
    features: "5 shelves, Easy assembly, Adjustable height, Powder coated, Anti-rust",
    frameThickness: "1.5mm", countryOfOrigin: "India", createdAt: "2024-01-03",
    imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=700&q=80",
  },
  {
    productId: "SKW-SF-004", productName: "Steel Filing Cabinet – 4 Drawer", category: "Steel Furniture Works",
    furnitureType: "Cabinet", steelGrade: "CRCA", surfaceFinish: "Powder Coated", color: "Beige",
    availability: "Available", finalPriceINR: 6800, basePriceINR: 7500, discountPercentage: 9,
    stockQuantity: 60, rating: 4.3, reviewsCount: 29, salesCount: 75,
    warrantyYears: 2, leadTimeDays: 7, customizationAvailable: "No",
    length_cm: 46, width_cm: 62, height_cm: 132, weight_kg: 28,
    loadCapacityKg: 80, usageArea: "Office", recommendedFor: "Document storage",
    productDescription: "4-drawer steel filing cabinet with central lock. A4/foolscap size folders fit perfectly.",
    features: "Central lock, 4 drawers, A4 compatible, Anti-tip mechanism, Smooth glide",
    frameThickness: "0.8mm", countryOfOrigin: "India", createdAt: "2024-01-04",
    imageUrl: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=700&q=80",
  },

  // ── Commercial Building Structures ─────────────────────────────
  {
    productId: "SKW-CB-001", productName: "Pre-Engineered Factory Shed Structure", category: "Commercial Building Structures",
    furnitureType: "", steelGrade: "IS 2062 E250", surfaceFinish: "Galvanised + Painted", color: "Grey/Blue",
    availability: "Made to Order", finalPriceINR: 850000, basePriceINR: 950000, discountPercentage: 10,
    stockQuantity: 5, rating: 4.8, reviewsCount: 12, salesCount: 18,
    warrantyYears: 10, leadTimeDays: 45, customizationAvailable: "Yes",
    length_cm: 3000, width_cm: 1500, height_cm: 700, weight_kg: 18000,
    loadCapacityKg: 500000, usageArea: "Industrial", recommendedFor: "Factory sheds, warehouses",
    productDescription: "Complete pre-engineered steel structure for factory sheds. Includes columns, rafters, purlins and girts.",
    features: "Pre-engineered, BIS certified steel, Includes roofing support, Wind load designed, Fast erection",
    frameThickness: "6mm+", countryOfOrigin: "India", createdAt: "2024-02-01",
    imageUrl: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=700&q=80",
  },
  {
    productId: "SKW-CB-002", productName: "Steel Warehouse Portal Frame", category: "Commercial Building Structures",
    furnitureType: "", steelGrade: "IS 2062 E350", surfaceFinish: "Primer + Epoxy", color: "Red Oxide",
    availability: "Made to Order", finalPriceINR: 1250000, basePriceINR: 1400000, discountPercentage: 11,
    stockQuantity: 3, rating: 4.9, reviewsCount: 8, salesCount: 11,
    warrantyYears: 15, leadTimeDays: 60, customizationAvailable: "Yes",
    length_cm: 5000, width_cm: 2400, height_cm: 900, weight_kg: 35000,
    loadCapacityKg: 1000000, usageArea: "Warehouse", recommendedFor: "Large warehouses",
    productDescription: "Heavy-duty steel portal frame warehouse structure. Designed for large spans without intermediate columns.",
    features: "Column-free interior, High span capacity, Crane gantry compatible, BIS steel, Fast delivery",
    frameThickness: "8mm+", countryOfOrigin: "India", createdAt: "2024-02-02",
    imageUrl: "https://images.unsplash.com/photo-1590859808308-3d2d9c515b1a?w=700&q=80",
  },

  // ── SS Railing ─────────────────────────────────────────────────
  {
    productId: "SKW-SR-001", productName: "SS 304 Glass Balcony Railing", category: "SS Railing",
    furnitureType: "", steelGrade: "SS 304", surfaceFinish: "Mirror Polish", color: "Silver",
    availability: "Available", finalPriceINR: 1800, basePriceINR: 2100, discountPercentage: 14,
    stockQuantity: 200, rating: 4.6, reviewsCount: 67, salesCount: 185,
    warrantyYears: 5, leadTimeDays: 7, customizationAvailable: "Yes",
    length_cm: 100, width_cm: 5, height_cm: 100, weight_kg: 4,
    loadCapacityKg: 100, usageArea: "Balcony, Terrace", recommendedFor: "Residential buildings",
    productDescription: "Stainless steel 304 grade glass balcony railing per running metre. Mirror polished finish. Glass channels included.",
    features: "SS 304 grade, Mirror polished, Glass compatible, Corrosion resistant, Easy installation",
    frameThickness: "1.2mm", countryOfOrigin: "India", createdAt: "2024-03-01",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=700&q=80",
  },
  {
    productId: "SKW-SR-002", productName: "SS 316 Staircase Railing System", category: "SS Railing",
    furnitureType: "", steelGrade: "SS 316", surfaceFinish: "Satin Finish", color: "Silver",
    availability: "Available", finalPriceINR: 2400, basePriceINR: 2800, discountPercentage: 14,
    stockQuantity: 180, rating: 4.8, reviewsCount: 43, salesCount: 120,
    warrantyYears: 7, leadTimeDays: 10, customizationAvailable: "Yes",
    length_cm: 100, width_cm: 5, height_cm: 100, weight_kg: 5.5,
    loadCapacityKg: 150, usageArea: "Staircase", recommendedFor: "Commercial/Coastal areas",
    productDescription: "Marine-grade SS 316 staircase railing. Ideal for coastal environments and commercial staircases.",
    features: "SS 316 marine grade, Satin finish, High corrosion resistance, Custom heights, BIS certified",
    frameThickness: "1.5mm", countryOfOrigin: "India", createdAt: "2024-03-02",
    imageUrl: "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=700&q=80",
  },
  {
    productId: "SKW-SR-003", productName: "SS Garden / Pool Railing", category: "SS Railing",
    furnitureType: "", steelGrade: "SS 202", surfaceFinish: "Brush Finish", color: "Silver-Grey",
    availability: "Available", finalPriceINR: 1200, basePriceINR: 1450, discountPercentage: 17,
    stockQuantity: 250, rating: 4.4, reviewsCount: 31, salesCount: 95,
    warrantyYears: 3, leadTimeDays: 5, customizationAvailable: "Yes",
    length_cm: 100, width_cm: 4, height_cm: 90, weight_kg: 3.2,
    loadCapacityKg: 80, usageArea: "Garden, Pool", recommendedFor: "Outdoor applications",
    productDescription: "Economical SS 202 grade railing for gardens and swimming pool edges. UV and weather resistant.",
    features: "SS 202 grade, Weather resistant, UV stable, Lightweight, Easy fix posts",
    frameThickness: "1mm", countryOfOrigin: "India", createdAt: "2024-03-03",
    imageUrl: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=700&q=80",
  },

  // ── Kitchen Trolleys ───────────────────────────────────────────
  {
    productId: "SKW-KT-001", productName: "SS 304 Commercial Kitchen Trolley", category: "Kitchen Trolleys",
    furnitureType: "Trolley", steelGrade: "SS 304", surfaceFinish: "Brushed Finish", color: "Silver",
    availability: "Available", finalPriceINR: 7500, basePriceINR: 8800, discountPercentage: 15,
    stockQuantity: 65, rating: 4.7, reviewsCount: 34, salesCount: 88,
    warrantyYears: 3, leadTimeDays: 7, customizationAvailable: "Yes",
    length_cm: 90, width_cm: 60, height_cm: 85, weight_kg: 18,
    loadCapacityKg: 100, usageArea: "Hotel Kitchen, Restaurant", recommendedFor: "Commercial kitchens",
    productDescription: "Heavy-duty SS 304 kitchen trolley with two shelves and locking castors. FSSAI compliant.",
    features: "SS 304, FSSAI compliant, Locking wheels, 2 shelves, Easy clean surface",
    frameThickness: "1.2mm", countryOfOrigin: "India", createdAt: "2024-04-01",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=700&q=80",
  },
  {
    productId: "SKW-KT-002", productName: "SS 304 Kitchen Work Table", category: "Kitchen Trolleys",
    furnitureType: "Table", steelGrade: "SS 304", surfaceFinish: "Brushed", color: "Silver",
    availability: "Available", finalPriceINR: 9800, basePriceINR: 11000, discountPercentage: 11,
    stockQuantity: 48, rating: 4.8, reviewsCount: 28, salesCount: 72,
    warrantyYears: 3, leadTimeDays: 10, customizationAvailable: "Yes",
    length_cm: 150, width_cm: 70, height_cm: 85, weight_kg: 25,
    loadCapacityKg: 200, usageArea: "Restaurant Kitchen", recommendedFor: "Food prep stations",
    productDescription: "SS 304 commercial kitchen work table with under-shelf. Welded legs, flat-pack optional.",
    features: "SS 304 top, Under shelf, Adjustable feet, Smooth weld, Custom sizes",
    frameThickness: "1.5mm", countryOfOrigin: "India", createdAt: "2024-04-02",
    imageUrl: "https://images.unsplash.com/photo-1565183928294-7063f23ce0f8?w=700&q=80",
  },
  {
    productId: "SKW-KT-003", productName: "Mobile Catering Service Trolley", category: "Kitchen Trolleys",
    furnitureType: "Trolley", steelGrade: "SS 304", surfaceFinish: "Mirror Polish", color: "Silver",
    availability: "Available", finalPriceINR: 5500, basePriceINR: 6200, discountPercentage: 11,
    stockQuantity: 90, rating: 4.5, reviewsCount: 19, salesCount: 55,
    warrantyYears: 2, leadTimeDays: 5, customizationAvailable: "Yes",
    length_cm: 80, width_cm: 45, height_cm: 95, weight_kg: 14,
    loadCapacityKg: 80, usageArea: "Banquet Hall, Hotel", recommendedFor: "Table service",
    productDescription: "Mobile 3-tier catering service trolley. Mirror-polished finish. Suitable for banquets and fine dining.",
    features: "3 tier shelves, Mirror finish, Silent rubber wheels, SS 304, Foldable handle",
    frameThickness: "1mm", countryOfOrigin: "India", createdAt: "2024-04-03",
    imageUrl: "https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=700&q=80",
  },

  // ── Hotel Furnitures ───────────────────────────────────────────
  {
    productId: "SKW-HF-001", productName: "Hotel Steel Bed Frame – King Size", category: "Hotel Furnitures",
    furnitureType: "Bed", steelGrade: "IS 2062", surfaceFinish: "Powder Coated", color: "Matte Black",
    availability: "Available", finalPriceINR: 14500, basePriceINR: 17000, discountPercentage: 15,
    stockQuantity: 35, rating: 4.6, reviewsCount: 22, salesCount: 65,
    warrantyYears: 5, leadTimeDays: 14, customizationAvailable: "Yes",
    length_cm: 196, width_cm: 182, height_cm: 50, weight_kg: 35,
    loadCapacityKg: 350, usageArea: "Hotel Room", recommendedFor: "Hotels, Resorts",
    productDescription: "King-size hotel steel bed frame with slatted base. Powder-coated finish in matte black. Noiseless joints.",
    features: "King size, Powder coated, Silent slat base, Floor protectors, Anti-rust, Custom headboard",
    frameThickness: "2mm", countryOfOrigin: "India", createdAt: "2024-05-01",
    imageUrl: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=700&q=80",
  },
  {
    productId: "SKW-HF-002", productName: "Hotel Steel Wardrobe – 3 Door", category: "Hotel Furnitures",
    furnitureType: "Wardrobe", steelGrade: "CRCA", surfaceFinish: "Powder Coated", color: "Ivory White",
    availability: "Available", finalPriceINR: 18500, basePriceINR: 21000, discountPercentage: 12,
    stockQuantity: 25, rating: 4.5, reviewsCount: 15, salesCount: 42,
    warrantyYears: 5, leadTimeDays: 14, customizationAvailable: "Yes",
    length_cm: 150, width_cm: 55, height_cm: 200, weight_kg: 55,
    loadCapacityKg: 100, usageArea: "Hotel Room", recommendedFor: "Hotels",
    productDescription: "3-door steel wardrobe for hotels. Includes hanging rail, shelf, and mirror. Powder coated in ivory white.",
    features: "3 doors, Mirror inside, Hanger rail, Adjustable shelf, Central lock, Anti-fingerprint finish",
    frameThickness: "0.8mm", countryOfOrigin: "India", createdAt: "2024-05-02",
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=700&q=80",
  },
  {
    productId: "SKW-HF-003", productName: "Hotel Lobby Steel Chair", category: "Hotel Furnitures",
    furnitureType: "Chair", steelGrade: "SS 304", surfaceFinish: "Satin Polish", color: "Silver",
    availability: "Available", finalPriceINR: 6200, basePriceINR: 7000, discountPercentage: 11,
    stockQuantity: 80, rating: 4.4, reviewsCount: 31, salesCount: 95,
    warrantyYears: 3, leadTimeDays: 10, customizationAvailable: "Yes",
    length_cm: 55, width_cm: 55, height_cm: 82, weight_kg: 8,
    loadCapacityKg: 150, usageArea: "Hotel Lobby", recommendedFor: "Hotels, Lounges",
    productDescription: "Elegant SS 304 lobby chair with cushioned seat. Satin polished frame. Premium hotel-grade finish.",
    features: "SS 304 frame, Satin polish, Cushioned seat, Stackable, Scratch resistant feet",
    frameThickness: "1.5mm", countryOfOrigin: "India", createdAt: "2024-05-03",
    imageUrl: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=700&q=80",
  },

  // ── Food Processing Machines ───────────────────────────────────
  {
    productId: "SKW-FP-001", productName: "SS 316 Storage Tank – 500 Litre", category: "Food Processing Machines",
    furnitureType: "", steelGrade: "SS 316L", surfaceFinish: "Mirror Polish", color: "Silver",
    availability: "Made to Order", finalPriceINR: 38000, basePriceINR: 45000, discountPercentage: 16,
    stockQuantity: 12, rating: 4.9, reviewsCount: 14, salesCount: 28,
    warrantyYears: 5, leadTimeDays: 21, customizationAvailable: "Yes",
    length_cm: 80, width_cm: 80, height_cm: 120, weight_kg: 45,
    loadCapacityKg: 500, usageArea: "Food Plant, Dairy", recommendedFor: "Food & beverage storage",
    productDescription: "Food-grade SS 316L vertical cylindrical storage tank. TIG welded, mirror polished inside. FSSAI compatible.",
    features: "SS 316L, TIG welded, Mirror inside, FSSAI compatible, Drain valve, Manhole cover",
    frameThickness: "3mm", countryOfOrigin: "India", createdAt: "2024-06-01",
    imageUrl: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=700&q=80",
  },
  {
    productId: "SKW-FP-002", productName: "SS Conveyor Belt System – 3m", category: "Food Processing Machines",
    furnitureType: "", steelGrade: "SS 304", surfaceFinish: "Brushed", color: "Silver",
    availability: "Made to Order", finalPriceINR: 55000, basePriceINR: 65000, discountPercentage: 15,
    stockQuantity: 8, rating: 4.7, reviewsCount: 9, salesCount: 16,
    warrantyYears: 3, leadTimeDays: 30, customizationAvailable: "Yes",
    length_cm: 300, width_cm: 50, height_cm: 90, weight_kg: 80,
    loadCapacityKg: 200, usageArea: "Food Processing Unit", recommendedFor: "Bakeries, packaging lines",
    productDescription: "3-metre SS 304 food-grade conveyor belt with variable speed motor. Easy-clean PU belt.",
    features: "SS 304 frame, PU food-grade belt, Variable speed, Adjustable height, IP55 motor",
    frameThickness: "2mm", countryOfOrigin: "India", createdAt: "2024-06-02",
    imageUrl: "https://images.unsplash.com/photo-1581093450021-4a7360e9a6b5?w=700&q=80",
  },

  // ── Park Instruments ───────────────────────────────────────────
  {
    productId: "SKW-PI-001", productName: "Galvanised Steel Swing Set – 3 Seater", category: "Park Instruments",
    furnitureType: "", steelGrade: "IS 2062", surfaceFinish: "Hot-Dip Galvanised + Painted", color: "Yellow/Blue",
    availability: "Available", finalPriceINR: 22000, basePriceINR: 25000, discountPercentage: 12,
    stockQuantity: 20, rating: 4.7, reviewsCount: 18, salesCount: 45,
    warrantyYears: 5, leadTimeDays: 10, customizationAvailable: "Yes",
    length_cm: 400, width_cm: 90, height_cm: 230, weight_kg: 65,
    loadCapacityKg: 300, usageArea: "Park, School", recommendedFor: "Children's playground",
    productDescription: "3-seater galvanised steel swing set as per IS 15567 standard. Weather-resistant paint. Anchor bolts included.",
    features: "IS 15567 compliant, Hot-dip galvanised, 3 swing seats, Anchor kit included, UV-stable paint",
    frameThickness: "3mm", countryOfOrigin: "India", createdAt: "2024-07-01",
    imageUrl: "https://images.unsplash.com/photo-1575783970733-1aaedde1db74?w=700&q=80",
  },
  {
    productId: "SKW-PI-002", productName: "Park Steel Bench – 6 Ft", category: "Park Instruments",
    furnitureType: "Bench", steelGrade: "IS 2062", surfaceFinish: "Powder Coated", color: "Green",
    availability: "Available", finalPriceINR: 5800, basePriceINR: 6800, discountPercentage: 15,
    stockQuantity: 55, rating: 4.6, reviewsCount: 42, salesCount: 110,
    warrantyYears: 5, leadTimeDays: 7, customizationAvailable: "Yes",
    length_cm: 180, width_cm: 55, height_cm: 80, weight_kg: 28,
    loadCapacityKg: 300, usageArea: "Park, Garden", recommendedFor: "Outdoor seating",
    productDescription: "6-foot outdoor park bench with cast-iron style MS legs and treated wooden slats. Powder-coated finish.",
    features: "Powder coated, Treated slats, Anti-rust legs, Ground anchors, Graffiti resistant",
    frameThickness: "4mm", countryOfOrigin: "India", createdAt: "2024-07-02",
    imageUrl: "https://images.unsplash.com/photo-1519331379826-f10be5486c6f?w=700&q=80",
  },
  {
    productId: "SKW-PI-003", productName: "Outdoor Gym Station – Multi Equipment", category: "Park Instruments",
    furnitureType: "", steelGrade: "IS 2062", surfaceFinish: "Hot-Dip Galvanised + Powder Coated", color: "Multi-colour",
    availability: "Made to Order", finalPriceINR: 85000, basePriceINR: 98000, discountPercentage: 13,
    stockQuantity: 8, rating: 4.8, reviewsCount: 11, salesCount: 22,
    warrantyYears: 7, leadTimeDays: 21, customizationAvailable: "Yes",
    length_cm: 500, width_cm: 200, height_cm: 250, weight_kg: 180,
    loadCapacityKg: 500, usageArea: "Public Park", recommendedFor: "Community fitness",
    productDescription: "Multi-station outdoor gym set with 6 exercise units: pull-up bar, tai-chi wheel, leg press, surfer, shoulder press, twister.",
    features: "6 units, Hot-dip galvanised, Bearing-based joints, IS safety compliant, Weather proof",
    frameThickness: "4mm", countryOfOrigin: "India", createdAt: "2024-07-03",
    imageUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=700&q=80",
  },
];

await Product.insertMany(products);
console.log(`✅ Seeded ${products.length} products with images!`);

const cats = [...new Set(products.map(p => p.category))];
cats.forEach(c => console.log(`  • ${c}: ${products.filter(p => p.category === c).length} products`));

await mongoose.disconnect();
process.exit(0);
